// eslint-disable-next-line no-unused-vars
/* global DisclosureMenu, Menubar, TopLinkDisclosureMenu, Treeview */

import BaseMenuToggle from "./_baseMenuToggle.js";
import BaseMenuItem from "./_baseMenuItem.js";
import {
  isValidInstance,
  isValidType,
  isQuerySelector,
  isValidClassList,
  isValidState,
  isValidEvent,
  isValidHoverType,
  isTag,
} from "./validate.js";
import { preventEvent, keyPress } from "./eventHandlers.js";
import StorageManager from "./StorageManager.js";

/**
 * An accessible navigation element in the DOM.
 *
 * This is intended to be used as a "base" to other menus and not to be used on
 * it's own in the DOM.
 */
class BaseMenu {
  /**
   * The class to use when generating submenus.
   *
   * @protected
   *
   * @type {typeof BaseMenu}
   */
  _MenuType = BaseMenu;

  /**
   * The class to use when generating menu items.
   *
   * @protected
   *
   * @type {typeof BaseMenuItem}
   */
  _MenuItemType = BaseMenuItem;

  /**
   * The class to use when generating submenu toggles.
   *
   * @protected
   *
   * @type {typeof BaseMenuToggle}
   */
  _MenuToggleType = BaseMenuToggle;

  /**
   * The DOM elements within the menu.
   *
   * @protected
   *
   * @type {Object<HTMLElement, HTMLElement[]>}
   *
   * @property {HTMLElement}   menu           - The menu element.
   * @property {HTMLElement[]} menuItems      - An array of menu items.
   * @property {HTMLElement[]} submenuItems   - An array of menu items that also contain submenu elements.
   * @property {HTMLElement[]} menuLinks      - An array of menu links.
   * @property {HTMLElement[]} submenuToggles - An array of menu links that function as submenu toggles.
   * @property {HTMLElement[]} submenus       - An array of submenu elements.
   * @property {HTMLElement}   controller     - The toggle for this menu.
   * @property {HTMLElement}   container      - The container for this menu.
   */
  _dom = {
    menu: null,
    menuItems: [],
    menuLinks: [],
    submenuItems: [],
    submenuToggles: [],
    submenus: [],
    controller: null,
    container: null,
  };

  /**
   * The DOM elements within the menu that cannot be reset or generated by the menu itself.
   *
   * @protected
   *
   * @type {string[]}
   */
  _protectedDOMElements = ["menu", "controller", "container"];

  /**
   * The query selectors used by the menu to populate the dom.
   *
   * @protected
   *
   * @type {Object<string>}
   *
   * @property {string} menuItems      - The query selector for menu items.
   * @property {string} menuLinks      - The query selector for menu links.
   * @property {string} submenuItems   - The query selector for menu items containing submenus.
   * @property {string} submenuToggles - The query selector for menu links that function as submenu toggles.
   * @property {string} submenus       - The query selector for for submenus.
   */
  _selectors = {
    menuItems: "",
    menuLinks: "",
    submenuItems: "",
    submenuToggles: "",
    submenus: "",
  };

  /**
   * The declared accessible-menu elements within the menu.
   *
   * @protected
   *
   * @type {Object<BaseMenu, BaseMenuToggle, BaseMenuItem[], BaseMenuToggle[]>}
   *
   * @property {BaseMenuItem[]}   menuItems      - An array of menu items.
   * @property {BaseMenuToggle[]} submenuToggles - An array of menu toggles.
   * @property {?BaseMenuToggle}  controller     - A menu toggle that controls this menu.
   * @property {?BaseMenu}        parentMenu     - The parent menu.
   * @property {?BaseMenu}        rootMenu       - The root menu of the menu tree.
   */
  _elements = {
    menuItems: [],
    submenuToggles: [],
    controller: null,
    parentMenu: null,
    rootMenu: null,
  };

  /**
   * The classes to apply when the menu is in various states.
   *
   * @protected
   *
   * @type {Object<string|string[]>}
   *
   * @property {string|string[]} open       - The class(es) to apply when the menu is open.
   * @property {string|string[]} close      - The class(es) to apply when the menu is closed.
   * @property {string|string[]} transition - The class(es) to apply when the menu is transitioning between states.
   */
  _classes = {
    open: "show",
    close: "hide",
    transition: "transitioning",
  };

  /**
   * The duration times (in milliseconds) for various menu transitions and events.
   *
   * @protected
   *
   * @type {Object<number>}
   *
   * @property {number} transition - The duration time (in milliseconds) for the transition between open and closed states.
   * @property {number} open       - The duration time (in milliseconds) for the transition from closed to open states.
   * @property {number} close      - The duration time (in milliseconds) for the transition from open to closed states.
   */
  _durations = {
    transition: 250,
    open: -1,
    close: -1,
  };

  /**
   * The delay times (in milliseconds) for various menu transitions and events.
   *
   * @protected
   *
   * @type {Object<number>}
   *
   * @property {number} hover      - The delay time (in milliseconds) used for pointerenter/pointerleave events to take place.
   * @property {number} enter      - The delay time (in milliseconds) used for pointerenter events to take place.
   * @property {number} leave      - The delay time (in milliseconds) used for pointerleave events to take place.
   */
  _delays = {
    hover: 250,
    enter: -1,
    leave: -1,
  };

  /**
   * A flag marking the root menu.
   *
   * @protected
   *
   * @type {boolean}
   */
  _root = true;

  /**
   * The index of the currently selected menu item in the menu.
   *
   * @protected
   *
   * @type {number}
   */
  _currentChild = 0;

  /**
   * The current state of the menu's focus.
   *
   * @protected
   *
   * @type {string}
   */
  _focusState = "none";

  /**
   * This last event triggered on the menu.
   *
   * @protected
   *
   * @type {string}
   */
  _currentEvent = "none";

  /**
   * The type of hoverability for the menu.
   *
   * @protected
   *
   * @type {string}
   */
  _hoverType = "off";

  /**
   * The prefix to use for CSS custom properties.
   *
   * @protected
   *
   * @type {string}
   */
  _prefix = "am-";

  /**
   * A flag to check if the menu can dynamically hover based on if a menu has been opened already.
   *
   * @protected
   *
   * @type {boolean}
   */
  _hasOpened = false;

  /**
   * Timeouts throughout the component.
   *
   * @protected
   *
   * @type {Object<Function>}
   */
  _timeouts = {};

  /**
   * Event listeners throughout the menu.
   *
   * @protected
   *
   * @type {object[]}
   */
  _listeners = [];

  /**
   * The key used to generate IDs throughout the menu.
   *
   * @protected
   *
   * @type {string}
   */
  _key = "";

  /**
   * The key used for storage.
   *
   * @protected
   *
   * @type {string}
   */
  _storageKey = "menus";

  /**
   * The main ID of the menu.
   *
   * @protected
   *
   * @type {string}
   */
  _id = "";

  /**
   * The validity state of the menu.
   *
   * @protected
   *
   * @type {boolean}
   */
  _valid = true;

  /**
   * An array of error messages generated by the menu.
   *
   * @protected
   *
   * @type {string[]}
   */
  _errors = [];

  /**
   * Constructs a new `BaseMenu`.
   *
   * @param {object}             options                                     - The options for generating the menu.
   * @param {HTMLElement}        options.menuElement                         - The menu element in the DOM.
   * @param {string}             [options.menuItemsSelector = li]            - The query selector string for menu items.
   * @param {string}             [options.menuLinksSelector = a]             - The query selector string for menu links.
   * @param {string}             [options.submenuItemsSelector = li:has(ul)] - The query selector string for menu items containing submenus.
   * @param {string}             [options.submenuTogglesSelector = a]        - The query selector string for submenu toggle buttons/links.
   * @param {string}             [options.submenusSelector = ul]             - The query selector string for submenus.
   * @param {?HTMLElement}       [options.controllerElement = null]          - The element controlling the menu in the DOM.
   * @param {?HTMLElement}       [options.containerElement = null]           - The element containing the menu in the DOM.
   * @param {?(string|string[])} [options.openClass = show]                  - The class to apply when a menu is "open".
   * @param {?(string|string[])} [options.closeClass = hide]                 - The class to apply when a menu is "closed".
   * @param {?(string|string[])} [options.transitionClass = transitioning]   - The class to apply when a menu is transitioning between "open" and "closed" states.
   * @param {number}             [options.transitionDuration = 250]          - The duration of the transition between "open" and "closed" states (in milliseconds).
   * @param {boolean}            [options.openDuration = -1]                 - The duration of the transition from "closed" to "open" states (in milliseconds).
   * @param {boolean}            [options.closeDuration = -1]                - The duration of the transition from "open" to "closed" states (in milliseconds).
   * @param {boolean}            [options.isTopLevel = false]                - A flag to mark the root menu.
   * @param {?BaseMenu}          [options.parentMenu = null]                 - The parent menu to this menu.
   * @param {string}             [options.hoverType = off]                   - The type of hoverability a menu has.
   * @param {number}             [options.hoverDelay = 250]                  - The delay for opening and closing menus if the menu is hoverable (in milliseconds).
   * @param {number}             [options.enterDelay = -1]                   - The delay for opening menus if the menu is hoverable (in milliseconds).
   * @param {number}             [options.leaveDelay = -1]                   - The delay for closing menus if the menu is hoverable (in milliseconds).
   * @param {?string}            [options.prefix = am-]                      - The prefix to use for CSS custom properties.
   * @param {?string}            [options.key = null]                        - The key used to generate IDs throughout the menu.
   */
  constructor({
    menuElement,
    menuItemsSelector = "li",
    menuLinksSelector = "a",
    submenuItemsSelector = "li:has(ul)",
    submenuTogglesSelector = "a",
    submenusSelector = "ul",
    controllerElement = null,
    containerElement = null,
    openClass = "show",
    closeClass = "hide",
    transitionClass = "transitioning",
    transitionDuration = 250,
    openDuration = -1,
    closeDuration = -1,
    isTopLevel = true,
    parentMenu = null,
    hoverType = "off",
    hoverDelay = 250,
    enterDelay = -1,
    leaveDelay = -1,
    prefix = "am-",
    key = null,
  }) {
    // Set DOM elements.
    this._dom.menu = menuElement;
    this._dom.controller = controllerElement;
    this._dom.container = containerElement;

    // Set DOM selectors.
    this._selectors.menuItems = menuItemsSelector;
    this._selectors.menuLinks = menuLinksSelector;
    this._selectors.submenuItems = submenuItemsSelector;
    this._selectors.submenuToggles = submenuTogglesSelector;
    this._selectors.submenus = submenusSelector;

    // Set menu elements.
    this._elements.menuItems = [];
    this._elements.submenuToggles = [];
    this._elements.controller = null;
    this._elements.parentMenu = parentMenu;
    this._elements.rootMenu = isTopLevel ? this : null;

    // Set open/close classes.
    this._classes.open = openClass || "";
    this._classes.close = closeClass || "";
    this._classes.transition = transitionClass || "";

    // Set transition duration.
    this._durations.transition = transitionDuration;
    this._durations.open = openDuration;
    this._durations.close = closeDuration;

    // Set the prefix and key.
    this._prefix = prefix || "";
    this._key = key || "";

    // Set root.
    this._root = isTopLevel;

    // Set hover settings.
    this._hoverType = hoverType;
    this._delays.hover = hoverDelay;
    this._delays.enter = enterDelay;
    this._delays.leave = leaveDelay;
  }

  /**
   * Initializes the menu.
   *
   * The following steps will be taken to initialize the menu:
   * - Validate that the menu can initialize.
   * - Find the root menu of the menu tree if it isn't already set.
   * - Populate all DOM elements within the dom.
   * - If the current menu is the root menu, set the ID's on the menu, controller,
   *   and container.
   * - If the current menu is the root menu _and_ has a controller, initialize
   *   the controller.
   * - If the current menu is the root menu, add it to the AccessibleMenu storage in the window.
   * - Populate the menu elements within the elements.
   * - Set the transition duration custom prop for the menu.
   *
   * @public
   *
   * @throws {Error} Will throw an Error if validate returns `false`.
   */
  initialize() {
    if (!this._validate()) {
      throw new Error(
        `AccessibleMenu: cannot initialize menu. The following errors have been found:\n - ${this.errors
          .map((error) => error.toString())
          .join("\n - ")}`
      );
    }

    // Get the root menu if it doesn't exist.
    if (this.elements.rootMenu === null) this._findRootMenu(this);

    // Generate the menu's key.
    this._generateKey();

    // Set all of the DOM elements.
    this._setDOMElements();

    if (this.isTopLevel) {
      // Set the root menu's IDs.
      this._setIds();

      if (this.dom.controller && this.dom.container) {
        // Create a new BaseMenuToggle to control the menu.
        const toggle = new this._MenuToggleType({
          menuToggleElement: this.dom.controller,
          parentElement: this.dom.container,
          controlledMenu: this,
        });

        // If the toggle isn't a button, add the appropriate role to let
        // screen readers know it should act like a button.
        if (
          !isTag(
            "button",
            { toggle: toggle.dom.toggle },
            { shouldThrow: false }
          ).status
        ) {
          toggle.dom.toggle.setAttribute("role", "button");
        }

        // Set the controller's aria attributes.
        // These aren't necessarily the same as the standard menu toggle.
        toggle.dom.toggle.setAttribute("aria-controls", this.dom.menu.id);

        this._elements.controller = toggle;
      }

      // Add the menu to a globally accessible list of menus.
      this._store();
    }

    this._createChildElements();
    this._setTransitionDurations();
  }

  /**
   * The DOM elements within the menu.
   *
   * @readonly
   *
   * @type {Object<HTMLElement, HTMLElement[]>}
   *
   * @see _dom
   */
  get dom() {
    return this._dom;
  }

  /**
   * The query selectors used by the menu to populate the dom.
   *
   * @readonly
   *
   * @type {Object<string>}
   *
   * @see _selectors
   */
  get selectors() {
    return this._selectors;
  }

  /**
   * The declared accessible-menu elements within the menu.
   *
   * @readonly
   *
   * @type {Object<BaseMenu, BaseMenuToggle, BaseMenuItem[], BaseMenuToggle[]>}
   *
   * @see _elements
   */
  get elements() {
    return this._elements;
  }

  /**
   * The classes to apply when the menu is in various states.
   *
   * @readonly
   *
   * @type {Object<string|string[]>}
   *
   * @see _classes
   */
  get classes() {
    return this._classes;
  }

  /**
   * The durations (in milliseconds) for various menu transitions and events.
   *
   * @readonly
   *
   * @type {Object<number>}
   *
   * @see _durations
   */
  get durations() {
    return this._durations;
  }

  /**
   * The delays (in milliseconds) for various menu transitions and events.
   *
   * @readonly
   *
   * @type {Object<number>}
   *
   * @see _delays
   */
  get delays() {
    return this._delays;
  }

  /**
   * Timeouts throughout the menu.
   *
   * @readonly
   *
   * @type {object}
   *
   * @see _timeouts
   */
  get timeouts() {
    return this._timeouts;
  }

  /**
   * Event listeners throughout the menu.
   *
   * @readonly
   *
   * @type {object[]}
   *
   * @see _listeners
   */
  get listeners() {
    return this._listeners;
  }

  /**
   * The flag marking the root menu.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _root
   */
  get isTopLevel() {
    return this._root;
  }

  /**
   * The key used to generate IDs throughout the menu.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their parent menu's key suffixed with their position.
   *
   * @readonly
   *
   * @type {string}
   *
   * @see _key
   */
  get key() {
    if (this.isTopLevel) {
      return this._key;
    }

    const position =
      this.elements.parentMenu.dom.submenus.indexOf(this.dom.menu) || 0;

    return `${this.elements.parentMenu.key}-${position}`;
  }

  /**
   * The main ID of the menu.
   *
   * @readonly
   *
   * @type {string}
   *
   * @see _id
   */
  get id() {
    return this._id;
  }

  /**
   * The validity state of the menu.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _valid
   */
  get isValid() {
    return this._valid;
  }

  /**
   * An array of error messages generated by the menu.
   *
   * @readonly
   *
   * @type {string[]}
   *
   * @see _errors
   */
  get errors() {
    return this._errors;
  }

  /**
   * The class(es) to apply when the menu is open.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's open class(es).
   *
   * @type {string|string[]}
   *
   * @see _classes.open
   */
  get openClass() {
    return this.isTopLevel
      ? this._classes.open
      : this.elements.rootMenu.openClass;
  }

  set openClass(value) {
    isValidClassList({ openClass: value });

    if (this._classes.open !== value) {
      this._classes.open = value;
    }
  }

  /**
   * The class(es) to apply when the menu is closed.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's close class(es).
   *
   * @type {string|string[]}
   *
   * @see _classes.close
   */
  get closeClass() {
    return this.isTopLevel
      ? this._classes.close
      : this.elements.rootMenu.closeClass;
  }

  set closeClass(value) {
    isValidClassList({ closeClass: value });

    if (this._classes.close !== value) {
      this._classes.close = value;
    }
  }

  /**
   * The class(es) to apply when the menu is transitioning between open and closed.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's transition class(es).
   *
   * @type {string|string[]}
   *
   * @see _classes.transition
   */
  get transitionClass() {
    return this.isTopLevel
      ? this._classes.transition
      : this.elements.rootMenu.transitionClass;
  }

  set transitionClass(value) {
    isValidClassList({ transitionClass: value });

    if (this._classes.transition !== value) {
      this._classes.transition = value;
    }
  }

  /**
   * The duration time (in milliseconds) for the transition between open and closed states.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's transition duration.
   *
   * Setting this value will also set the --am-transition-duration CSS custom property on the menu.
   *
   * @type {number}
   *
   * @see _durations.transition
   */
  get transitionDuration() {
    return this.isTopLevel
      ? this._durations.transition
      : this.elements.rootMenu.transitionDuration;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value) {
      this._durations.transition = value;
      this._setTransitionDurations();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from closed to open states.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's openDuration.
   *
   * If openDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --am-open-transition-duration CSS custom property on the menu.
   *
   * @type {number}
   *
   * @see _durations.open
   */
  get openDuration() {
    if (this._durations.open === -1) return this.transitionDuration;

    return this.isTopLevel
      ? this._durations.open
      : this.elements.rootMenu.openDuration;
  }

  set openDuration(value) {
    isValidType("number", { openDuration: value });

    if (this._durations.open !== value) {
      this._durations.open = value;
      this._setTransitionDurations();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from open to closed states.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's closeDuration.
   *
   * If closeDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --am-close-transition-duration CSS custom property on the menu.
   *
   * @type {number}
   *
   * @see _durations.close
   */
  get closeDuration() {
    if (this._durations.close === -1) return this.transitionDuration;

    return this.isTopLevel
      ? this._durations.close
      : this.elements.rootMenu.closeDuration;
  }

  set closeDuration(value) {
    isValidType("number", { closeDuration: value });

    if (this._durations.close !== value) {
      this._durations.close = value;
      this._setTransitionDurations();
    }
  }

  /**
   * The index of the currently selected menu item in the menu.
   *
   * - Attempting to set a value less than -1 will set the current child to -1.
   * - Attempting to set a value greater than or equal to the number of menu items
   *   will set the current child to the index of the last menu item in the menu.
   *
   * If the current menu has a parent menu _and_ the menu's
   * current event is "mouse", The parent menu
   * will have it's current child updated as well to help with transitioning
   * between mouse and keyboard navigation.
   *
   * @type {number}
   *
   * @see _currentChild
   */
  get currentChild() {
    return this._currentChild;
  }

  set currentChild(value) {
    isValidType("number", { currentChild: value });

    /**
     * Update the parent menu's current child to make sure clicks
     * and other jumps don't interfere with keyboard navigation.
     *
     * @param {BaseMenu} menu - The initial menu.
     */
    function setParentChild(menu) {
      const updateEvents = ["mouse", "character"];

      if (
        updateEvents.includes(menu.currentEvent) &&
        menu.elements.parentMenu
      ) {
        let index = 0;
        let found = false;

        while (
          !found &&
          index < menu.elements.parentMenu.elements.menuItems.length
        ) {
          const menuItem = menu.elements.parentMenu.elements.menuItems[index];

          if (
            menuItem.isSubmenuItem &&
            menuItem.elements.toggle.elements.controlledMenu === menu
          ) {
            found = true;

            menu.elements.parentMenu.currentEvent = menu.currentEvent;
            menu.elements.parentMenu.currentChild = index;
          }

          index++;
        }
      }
    }

    if (value < -1) {
      this._currentChild = -1;
      setParentChild(this);
    } else if (value >= this.elements.menuItems.length) {
      this._currentChild = this.elements.menuItems.length - 1;
      setParentChild(this);
    } else if (this.focusChild !== value) {
      this._currentChild = value;
      setParentChild(this);
    }
  }

  /**
   * The current state of the menu's focus.
   *
   * - If the menu has submenus, setting the focus state to "none" or "self" will
   *   update all child menus to have the focus state of "none".
   * - If the menu has a parent menu, setting the focus state to "self" or "child"
   *   will update all parent menus to have the focus state of "child".
   *
   * @type {string}
   *
   * @see _focusState
   */
  get focusState() {
    return this._focusState;
  }

  set focusState(value) {
    isValidState({ focusState: value });

    if (this._focusState !== value) {
      this._focusState = value;
    }

    if (
      this.elements.submenuToggles.length > 0 &&
      (value === "self" || value === "none")
    ) {
      this.elements.submenuToggles.forEach((toggle) => {
        toggle.elements.controlledMenu.focusState = "none";
      });
    }

    if (this.elements.parentMenu && (value === "self" || value === "child")) {
      this.elements.parentMenu.focusState = "child";
    }
  }

  /**
   * The last event triggered on the menu.
   *
   * @type {string}
   *
   * @see _currentEvent
   */
  get currentEvent() {
    return this._currentEvent;
  }

  set currentEvent(value) {
    isValidEvent({ currentEvent: value });

    if (this._currentEvent !== value) {
      this._currentEvent = value;

      if (this.elements.submenuToggles.length > 0) {
        this.elements.submenuToggles.forEach((submenuToggle) => {
          submenuToggle.elements.controlledMenu.currentEvent = value;
        });
      }
    }
  }

  /**
   * The currently selected menu item.
   *
   * @readonly
   *
   * @type {BaseMenuItem}
   */
  get currentMenuItem() {
    return this.elements.menuItems[this.currentChild];
  }

  /**
   * The type of hoverability for the menu.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's hoverability.
   *
   * @type {string}
   *
   * @see _hoverType
   */
  get hoverType() {
    return this._root ? this._hoverType : this.elements.rootMenu.hoverType;
  }

  set hoverType(value) {
    isValidHoverType({ hoverType: value });

    if (this._hoverType !== value) {
      this._hoverType = value;
    }
  }

  /**
   * The delay time (in milliseconds) used for pointerenter/pointerleave events to take place.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's hover delay.
   *
   * @type {number}
   *
   * @see _delays.hover
   */
  get hoverDelay() {
    return this._root ? this._delays.hover : this.elements.rootMenu.hoverDelay;
  }

  set hoverDelay(value) {
    isValidType("number", { hoverDelay: value });

    if (this._delays.hover !== value) {
      this._delays.hover = value;
    }
  }

  /**
   * The delay time (in milliseconds) used for pointerenter events to take place.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's enter delay.
   *
   * If enterDelay is set to -1, the hoverDelay value will be used instead.
   *
   * @type {number}
   *
   * @see _delays.enter
   */
  get enterDelay() {
    if (this._delays.enter === -1) return this.hoverDelay;

    return this._root ? this._delays.enter : this.elements.rootMenu.enterDelay;
  }

  set enterDelay(value) {
    isValidType("number", { enterDelay: value });

    if (this._delays.enter !== value) {
      this._delays.enter = value;
    }
  }

  /**
   * The delay time (in milliseconds) used for pointerleave events to take place.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's leave delay.
   *
   * If leaveDelay is set to -1, the hoverDelay value will be used instead.
   *
   * @type {number}
   *
   * @see _delays.leave
   */
  get leaveDelay() {
    if (this._delays.leave === -1) return this.hoverDelay;

    return this._root ? this._delays.leave : this.elements.rootMenu.leaveDelay;
  }

  set leaveDelay(value) {
    isValidType("number", { leaveDelay: value });

    if (this._delays.leave !== value) {
      this._delays.leave = value;
    }
  }

  /**
   * The prefix to use for CSS custom properties.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's prefix.
   *
   * @type {string}
   *
   * @see _prefix
   */
  get prefix() {
    return this._root ? this._prefix : this.elements.rootMenu.prefix;
  }

  set prefix(value) {
    isValidType("string", { prefix: value });

    if (this._prefix !== value) {
      this._prefix = value;
    }
  }

  /**
   * A flag to check if the menu's focus methods should _actually_ move the focus in the DOM.
   *
   * This will be `false` unless any of the following criteria are met:
   * - The menu's current event is "keyboard".
   * - The menu's current event is "character".
   * - The menu's current event is "mouse" _and_ the menu's
   *   hover type is "dynamic".
   *
   * @readonly
   *
   * @type {boolean}
   */
  get shouldFocus() {
    let check = false;

    if (this.currentEvent === "keyboard" || this.currentEvent === "character") {
      check = true;
    }

    if (this.currentEvent === "mouse" && this.hoverType === "dynamic") {
      check = true;
    }

    return check;
  }

  /**
   * A flag to check if the menu can dynamically hover.
   *
   * This functions differently for root vs. submenus.
   * Submenus will always inherit their root menu's hasOpened.
   *
   * @type {boolean}
   *
   * @see _hasOpened
   */
  get hasOpened() {
    return this._root ? this._hasOpened : this.elements.rootMenu.hasOpened;
  }

  set hasOpened(value) {
    isValidType("boolean", { hasOpened: value });

    if (this._hasOpened !== value) {
      this._hasOpened = value;
    }
  }

  /**
   * Validates all aspects of the menu to ensure proper functionality.
   *
   * @protected
   *
   * @return {boolean} - The result of the validation.
   */
  _validate() {
    // DOM checks.
    if (Object.keys(this._dom).length > 0) {
      const domElements = {};

      // Loop through and add "Element" to the end of each key in _dom.
      for (const domKey of Object.keys(this._dom)) {
        // If we're dealing with an array, we need to check each element in the array.
        if (Array.isArray(this._dom[domKey])) {
          this._dom[domKey].forEach((element, index) => {
            domElements[`${domKey}Element[${index}]`] = element;
          });
        } else {
          domElements[`${domKey}Element`] = this._dom[domKey];
        }
      }

      // Account for controller and container being nullable (together).
      if (
        domElements.controllerElement === null &&
        domElements.containerElement === null
      ) {
        delete domElements.controllerElement;
        delete domElements.containerElement;
      }

      // Check the DOM elements.
      const domChecks = isValidInstance(HTMLElement, domElements, {
        shouldThrow: false,
      });

      // Handle DOM check failure.
      if (!domChecks.status) {
        this._errors = [...this._errors, ...domChecks.errors];
        this._valid = false;
      }
    }

    // Query selector checks.
    if (Object.keys(this._selectors).length > 0) {
      const querySelectors = {};

      // Loop through and add "Selector" to the end of each key in _selectors.
      for (const querySelector of Object.keys(this._selectors)) {
        querySelectors[`${querySelector}Selector`] =
          this._selectors[querySelector];
      }

      // Check the query selectors.
      const querySelectorChecks = isQuerySelector(querySelectors, {
        shouldThrow: false,
      });

      // Handle query selector check failure.
      if (!querySelectorChecks.status) {
        this._errors = [...this._errors, ...querySelectorChecks.errors];
        this._valid = false;
      }
    }

    // Class list checks.
    if (Object.keys(this._classes).length > 0) {
      const classes = {};

      // Loop through and add "Class" to the end of each key in _classes.
      for (const className of Object.keys(this._classes)) {
        if (this._classes[className] === "") {
          continue;
        }

        classes[`${className}Class`] = this._classes[className];
      }

      // Check the class lists.
      const classListChecks = isValidClassList(classes, { shouldThrow: false });

      // Handle class list check failure.
      if (!classListChecks.status) {
        this._errors = [...this._errors, ...classListChecks.errors];
        this._valid = false;
      }
    }

    // Duration checks.
    if (Object.keys(this._durations).length > 0) {
      const durations = {};

      // Loop through and add "Duration" to the end of each key in _durations.
      for (const durationName of Object.keys(this._durations)) {
        durations[`${durationName}Duration`] = this._durations[durationName];
      }

      // Check the durations.
      const durationChecks = isValidType("number", durations, {
        shouldThrow: false,
      });

      // Handle duration check failure.
      if (!durationChecks.status) {
        this._errors = [...this._errors, ...durationChecks.errors];
        this._valid = false;
      }
    }

    // Delay checks.
    if (Object.keys(this._delays).length > 0) {
      const delays = {};

      // Loop through and add "Delay" to the end of each key in delays.
      for (const delayName of Object.keys(this._delays)) {
        delays[`${delayName}Delay`] = this._delays[delayName];
      }

      // Check the delays.
      const delayChecks = isValidType("number", delays, { shouldThrow: false });

      // Handle delay check failure.
      if (!delayChecks.status) {
        this._errors = [...this._errors, ...delayChecks.errors];
        this._valid = false;
      }
    }

    // Boolean checks.
    const booleans = {
      isTopLevel: this._root,
    };

    // Check the booleans.
    const booleanChecks = isValidType("boolean", booleans, {
      shouldThrow: false,
    });

    // Handle boolean check failure.
    if (!booleanChecks.status) {
      this._errors = [...this._errors, ...booleanChecks.errors];
      this._valid = false;
    }

    // Parent menu check.
    if (this._elements.parentMenu !== null) {
      // Check the parent menu.
      const parentCheck = isValidInstance(
        BaseMenu,
        {
          parentMenu: this._elements.parentMenu,
        },
        { shouldThrow: false }
      );

      // Handle parent menu check failure.
      if (!parentCheck.status) {
        this._errors = [...this._errors, ...parentCheck.errors];
        this._valid = false;
      }
    }

    // Hover type check.
    // Check the hover type.
    const hoverTypeCheck = isValidHoverType(
      { hoverType: this._hoverType },
      { shouldThrow: false }
    );

    // Handle hover type check failure.
    if (!hoverTypeCheck.status) {
      this._errors = [...this._errors, ...hoverTypeCheck.errors];
      this._valid = false;
    }

    // Key check.
    if (this._key !== "") {
      // Check the key.
      const keyCheck = isValidType(
        "string",
        { key: this._key },
        { shouldThrow: false }
      );

      // Handle key check failure.
      if (!keyCheck.status) {
        this._errors = [...this._errors, ...keyCheck.errors];
        this._valid = false;
      }
    }

    // Prefix check.
    if (this._prefix !== "") {
      const prefixCheck = isValidType(
        "string",
        { prefix: this._prefix },
        { shouldThrow: false }
      );

      if (!prefixCheck.status) {
        this._errors = [...this._errors, ...prefixCheck.errors];
        this._valid = false;
      }
    }

    return this._valid;
  }

  /**
   * Sets DOM elements throughout the menu.
   *
   * Elements listed in _protectedDOMElements cannot be set using this method.
   *
   * @protected
   *
   * @param {string}                      elementType                       - The type of element to populate.
   * @param {Object<HTMLElement,boolean>} [options = {}]                    - The options for setting the DOM element type.
   * @param {HTMLElement}                 [options.context = this.dom.menu] - The element used as the base context for the querySelector.
   * @param {boolean}                     [options.overwrite = true]        - A flag to set if the existing elements will be overwritten.
   * @param {boolean}                     [options.strict = true]           - A flag to set if the elements must be direct children of the base.
   */
  _setDOMElementType(
    elementType,
    { context = this.dom.menu, overwrite = true, strict = true } = {}
  ) {
    // Make sure the element type is valid.
    if (typeof this.selectors[elementType] !== "string") {
      throw new Error(
        `AccessibleMenu: "${elementType}" is not a valid element type.`
      );
    }

    // Make sure the element type can actually be set through this method.
    if (this._protectedDOMElements.includes(elementType)) {
      throw new Error(
        `AccessibleMenu: "${elementType}" element cannot be set through _setDOMElementType because it is a protected element.`
      );
    }

    // Make sure the context element is actually an HTMLELement.
    isValidInstance(HTMLElement, { context });

    // Get the all elements matching the selector in the context.
    const domElements = Array.from(
      context.querySelectorAll(this.selectors[elementType])
    );

    // Filter the elements so if `strict` is true, only direct children of the context are kept.
    const filteredElements = domElements.filter((item) =>
      strict ? item.parentElement === context : true
    );

    if (Array.isArray(this._dom[elementType])) {
      if (overwrite) {
        this._dom[elementType] = filteredElements;
      } else {
        this._dom[elementType] = [
          ...this._dom[elementType],
          ...filteredElements,
        ];
      }
    } else {
      this._dom[elementType] = filteredElements[0] || null;
    }
  }

  /**
   * Resets DOM elements throughout the menu.
   *
   * Elements listed in _protectedDOMElements cannot be reset using this method.
   *
   * @protected
   *
   * @param {string} elementType - The type of element to clear.
   */
  _resetDOMElementType(elementType) {
    // Make sure the element type is valid.
    if (typeof this.selectors[elementType] !== "string") {
      throw new Error(
        `AccessibleMenu: "${elementType}" is not a valid element type.`
      );
    }

    // Make sure the element type can actually be reset through this method.
    if (this._protectedDOMElements.includes(elementType)) {
      throw new Error(
        `AccessibleMenu: "${elementType}" element cannot be reset through _resetDOMElementType because it is a protected element.`
      );
    }

    if (Array.isArray(this._dom[elementType])) {
      this._dom[elementType] = [];
    } else {
      this._dom[elementType] = null;
    }
  }

  /**
   * Sets all DOM elements within the menu.
   *
   * Utilizes _setDOMElementType and
   * _resetDOMElementType.
   *
   * @protected
   */
  _setDOMElements() {
    this._setDOMElementType("menuItems");

    if (this.selectors.submenuItems !== "") {
      this._setDOMElementType("submenuItems");

      this._resetDOMElementType("submenuToggles");
      this._resetDOMElementType("submenus");

      this.dom.submenuItems.forEach((item) => {
        this._setDOMElementType("submenuToggles", {
          context: item,
          overwrite: false,
        });
        this._setDOMElementType("submenus", {
          context: item,
          overwrite: false,
        });
      });
    }
  }

  /**
   * Generates a key for the menu.
   *
   * @param {boolean} [regenerate = false] - A flag to determine if the key should be regenerated.
   */
  _generateKey(regenerate = false) {
    if (this.key === "" || regenerate) {
      this._key = Math.random()
        .toString(36)
        .replace(/[^a-z]+/g, "")
        .substring(0, 10);
    }
  }

  /**
   * Sets the IDs of the menu and it's elements if they do not already exist.
   *
   * The generated IDs use the key and follow the format:
   *  - menu: `menu-${key}`
   *  - container: `menu-container-${key}`
   *  - controller: `menu-controller-${key}`
   */
  _setIds() {
    this.dom.menu.id = this.dom.menu.id || `menu-${this.key}`;

    if (this.dom.container) {
      this.dom.container.id =
        this.dom.container.id || `menu-container-${this.key}`;
    }

    if (this.dom.controller) {
      this.dom.controller.id =
        this.dom.controller.id || `menu-controller-${this.key}`;
    }

    this._id = this.dom.menu.id;
  }

  /**
   * Finds the root menu element.
   *
   * @protected
   *
   * @param {BaseMenu} menu - The menu to check.
   */
  _findRootMenu(menu) {
    if (menu.isTopLevel) {
      this._elements.rootMenu = menu;
    } else if (menu.elements.parentMenu !== null) {
      this._findRootMenu(menu.elements.parentMenu);
    } else {
      throw new Error("Cannot find root menu.");
    }
  }

  /**
   * Creates and initializes all menu items and submenus.
   *
   * @protected
   */
  _createChildElements() {
    this.dom.menuItems.forEach((element) => {
      let menuItem;

      if (this.dom.submenuItems.includes(element)) {
        // The menu's toggle controller DOM element.
        const toggler = element.querySelector(this.selectors.submenuToggles);
        // The actual menu DOM element.
        const submenu = element.querySelector(this.selectors.submenus);

        // Create the new menu and initialize it.
        const menu = new this._MenuType({
          menuElement: submenu,
          menuItemsSelector: this.selectors.menuItems,
          menuLinksSelector: this.selectors.menuLinks,
          submenuItemsSelector: this.selectors.submenuItems,
          submenuTogglesSelector: this.selectors.submenuToggles,
          submenusSelector: this.selectors.submenus,
          openClass: this.openClass,
          closeClass: this.closeClass,
          transitionClass: this.transitionClass,
          transitionDuration: this.transitionDuration,
          openDuration: this.openDuration,
          closeDuration: this.closeDuration,
          isTopLevel: false,
          parentMenu: this,
          hoverType: this.hoverType,
          hoverDelay: this.hoverDelay,
          enterDelay: this.enterDelay,
          leaveDelay: this.leaveDelay,
        });

        // Create the new menu toggle.
        const toggle = new this._MenuToggleType({
          menuToggleElement: toggler,
          parentElement: element,
          controlledMenu: menu,
          parentMenu: this,
        });

        // Add the toggle to the list of toggles.
        this._elements.submenuToggles.push(toggle);

        // Create a new menu item.
        menuItem = new this._MenuItemType({
          menuItemElement: element,
          menuLinkElement: toggler,
          parentMenu: this,
          isSubmenuItem: true,
          childMenu: menu,
          toggle,
        });
      } else {
        const link = element.querySelector(this.selectors.menuLinks);

        // Create a new menu item.
        menuItem = new this._MenuItemType({
          menuItemElement: element,
          menuLinkElement: link,
          parentMenu: this,
        });
      }

      this._elements.menuItems.push(menuItem);
    });
  }

  /**
   * Handles focus events throughout the menu for proper menu use.
   *
   * - Adds a `focus` listener to every menu item so when it gains focus,
   *   it will set the item's containing menu's focus state
   *   to "self".
   * - Adds a `focusout` listener to the menu so when the menu loses focus,
   *   it will close.
   *
   * @protected
   */
  _handleFocus() {
    this.elements.menuItems.forEach((menuItem, index) => {
      this._addEventListener("focus", menuItem.dom.link, () => {
        this.focusState = "self";
        this.currentChild = index;
      });
    });

    this._addEventListener("focusout", this.dom.menu, (event) => {
      if (
        this.currentEvent !== "keyboard" ||
        event.relatedTarget === null ||
        this.dom.menu.contains(event.relatedTarget)
      ) {
        return;
      }

      this.focusState = "none";
      this.closeChildren();
    });
  }

  /**
   * Handles click events throughout the menu for proper use.
   *
   * - Adds a `click` listener to every menu item that will blur
   *   all menu items in the entire menu structure (starting at the root menu) and
   *   then properly focus the clicked item.
   * - Adds a `click` listener to every submenu item that will properly
   *   toggle the submenu open/closed.
   * - Adds a `click` listener to the menu's controller
   *   (if the menu is the root menu) so when it is clicked it will properly
   *   toggle open/closed.
   *
   * @protected
   */
  _handleClick() {
    /**
     * Toggles a toggle element.
     *
     * @param {BaseMenu}       menu   - This menu.
     * @param {BaseMenuToggle} toggle - The menu toggle
     * @param {Event}          event  - A Javascript event.
     */
    function toggleToggle(menu, toggle, event) {
      preventEvent(event);

      if (event.button !== 0) {
        return;
      }

      toggle.toggle();

      if (toggle.isOpen) {
        menu.focusState = "self";
        toggle.elements.controlledMenu.focusState = "none";
      }
    }

    this.elements.menuItems.forEach((item, index) => {
      // Properly focus the current menu item.
      this._addEventListener(
        "click",
        item.dom.link,
        () => {
          this.currentEvent = "mouse";
          this.elements.rootMenu.blurChildren();
          this._clearTimeout();
          this.focusChild(index);
        },
        { passive: true }
      );

      // Properly toggle submenus open and closed.
      if (item.isSubmenuItem) {
        this._addEventListener(
          "click",
          item.elements.toggle.dom.toggle,
          (event) => {
            this.currentEvent = "mouse";
            toggleToggle(this, item.elements.toggle, event);
          }
        );
      }
    });

    // Open the this menu if it's controller is clicked.
    if (this.isTopLevel && this.elements.controller) {
      this._addEventListener(
        "click",
        this.elements.controller.dom.toggle,
        (event) => {
          this.currentEvent = "mouse";
          toggleToggle(this, this.elements.controller, event);
        }
      );
    }

    // If the menu has no open children, set hasOpened to false.
    this._addEventListener("click", document, (event) => {
      if (this.focusState !== "none") {
        this.currentEvent = "mouse";

        if (
          !this.dom.menu.contains(event.target) &&
          !this.dom.menu !== event.target
        ) {
          this.elements.rootMenu.hasOpened = this.elements.submenuToggles.some(
            (toggle) => toggle.isOpen
          );
        }
      }
    });
  }

  /**
   * Handles hover events throughout the menu for proper use.
   *
   * Adds `pointerenter` listeners to all menu items and `pointerleave` listeners
   * to all submenu items which function differently depending on
   * the menu's hover type.
   *
   * Before executing anything, the event is checked to make sure the event wasn't
   * triggered by a pen or touch.
   *
   * <strong>Hover Type "on"</strong>
   * - When a `pointerenter` event triggers on any menu item the menu's
   *    current child value will change to that
   *   menu item.
   * - When a `pointerenter` event triggers on a submenu item the
   *   preview method for the submenu item's
   *   toggle will be called.
   * - When a `pointerleave` event triggers on an open submenu item the
   *   close method for the submenu item's toggle
   *   will be called after a delay set by the menu's hover delay.
   *
   * <strong>Hover Type "dynamic"</strong>
   * - When a `pointerenter` event triggers on any menu item the menu's
   *   current child value will change to that menu item.
   * - When a `pointerenter` event triggers on any menu item, and the menu's
   *   focus state is not "none", the menu item
   *   will be focused.
   * - When a `pointerenter` event triggers on a submenu item, and a submenu is
   *   already open, the preview method for the submenu item's toggle will be called.
   * - When a `pointerenter` event triggers on a non-submenu item, and a submenu
   *   is already open, the closeChildren method for the menu will be called.
   * - When a `pointerenter` event triggers on a submenu item, and no submenu is
   *   open, no submenu-specific methods will be called.
   * - When a `pointerleave` event triggers on an open submenu item that is not a
   *   root-level submenu item the close method for the submenu item's toggle
   *   will be called and the submenu item will be focused after a delay set by
   *   the menu's hover delay.
   * - When a `pointerleave` event triggers on an open submenu item that is a
   *   root-level submenu item no submenu-specific methods will be called.
   *
   * <strong>Hover Type "off"</strong>
   * All `pointerenter` and `pointerleave` events are ignored.
   *
   * @protected
   */
  _handleHover() {
    this.elements.menuItems.forEach((menuItem, index) => {
      this._addEventListener("pointerenter", menuItem.dom.link, (event) => {
        // Exit out of the event if it was not made by a mouse.
        if (event.pointerType === "pen" || event.pointerType === "touch") {
          return;
        }

        if (this.hoverType === "on") {
          this.currentEvent = "mouse";
          this.elements.rootMenu.blurChildren();
          this.focusChild(index);

          if (menuItem.isSubmenuItem) {
            if (this.enterDelay > 0) {
              this._clearTimeout();
              this._setTimeout(() => {
                menuItem.elements.toggle.preview();
              }, this.enterDelay);
            } else {
              menuItem.elements.toggle.preview();
            }
          }
        } else if (this.hoverType === "dynamic") {
          this.currentChild = index;

          if (!this.isTopLevel || this.focusState !== "none") {
            this.currentEvent = "mouse";
            this.elements.rootMenu.blurChildren();
            this.focusCurrentChild();
          }

          if (!this.isTopLevel || this.hasOpened) {
            this.currentEvent = "mouse";
            this.elements.rootMenu.blurChildren();
            this.focusCurrentChild();

            if (menuItem.isSubmenuItem) {
              if (this.enterDelay > 0) {
                this._clearTimeout();
                this._setTimeout(() => {
                  menuItem.elements.toggle.preview();
                }, this.enterDelay);
              } else {
                menuItem.elements.toggle.preview();
              }
            } else {
              if (this.enterDelay > 0) {
                this._clearTimeout();
                this._setTimeout(() => {
                  this.closeChildren();
                }, this.enterDelay);
              } else {
                this.closeChildren();
              }
            }
          }
        }
      });

      if (menuItem.isSubmenuItem) {
        this._addEventListener("pointerleave", menuItem.dom.item, (event) => {
          // Exit out of the event if it was not made by a mouse.
          if (event.pointerType === "pen" || event.pointerType === "touch") {
            return;
          }

          if (this.hoverType === "on") {
            if (this.leaveDelay > 0) {
              this._clearTimeout();
              this._setTimeout(() => {
                this.currentEvent = "mouse";
                menuItem.elements.toggle.close();
              }, this.leaveDelay);
            } else {
              this.currentEvent = "mouse";
              menuItem.elements.toggle.close();
            }
          } else if (this.hoverType === "dynamic") {
            if (this.leaveDelay > 0) {
              this._clearTimeout();
              this._setTimeout(() => {
                this.currentEvent = "mouse";
              }, this.leaveDelay);
            } else {
              this.currentEvent = "mouse";
            }
          }
        });

        // Clear hover timeouts any time the mouse enters an item with a submenu. This prevents the
        // menu from closing if the mouse leaves but then re-enters before leaveDelay has elapsed.
        this._addEventListener("pointerenter", menuItem.dom.item, (event) => {
          // Exit out of the event if it was not made by a mouse.
          if (event.pointerType === "pen" || event.pointerType === "touch") {
            return;
          }
          if (
            menuItem.isSubmenuItem &&
            (this.hoverType === "on" || this.hoverType === "dynamic") &&
            this.leaveDelay > 0
          ) {
            this._clearTimeout();
          }
        });
      }
    });
  }

  /**
   * Handles keydown events throughout the menu for proper menu use.
   *
   * This method exists to assist the _handleKeyup method.
   *
   * - Adds a `keydown` listener to the menu's controller (if the menu is the root menu).
   *   - Blocks propagation on "Space", "Enter", and "Escape" keys.
   *
   * @protected
   */
  _handleKeydown() {
    if (this.isTopLevel && this.elements.controller) {
      this._addEventListener(
        "keydown",
        this.elements.controller.dom.toggle,
        (event) => {
          this.currentEvent = "keyboard";

          const key = keyPress(event);

          if (key === "Space" || key === "Enter") {
            preventEvent(event);
          }
        }
      );
    }
  }

  /**
   * Handles keyup events throughout the menu for proper menu use.
   *
   * - Adds a `keyup` listener to the menu's controller (if the menu is the root menu).
   *   - Toggles the menu when the user hits "Space" or "Enter".
   *
   * @protected
   */
  _handleKeyup() {
    if (this.isTopLevel && this.elements.controller) {
      this._addEventListener(
        "keyup",
        this.elements.controller.dom.toggle,
        (event) => {
          this.currentEvent = "keyboard";

          const key = keyPress(event);

          if (key === "Space" || key === "Enter") {
            preventEvent(event);
            this.elements.controller.toggle();

            // If the menu is open, focus the first child.
            if (this.elements.controller.isOpen) {
              this.focusFirstChild();
            }
          }
        }
      );
    }
  }

  /**
   * Stores the menu into the global storage object.
   *
   * @protected
   */
  _store() {
    // Set up the storage.
    if (
      !isValidInstance(
        StorageManager,
        { storage: window.AccessibleMenu },
        { shouldThrow: false }
      ).status
    ) {
      new StorageManager({ scope: "AccessibleMenu", type: this._storageKey });
    }

    // Store the menu
    window.AccessibleMenu.set({
      key: this.id !== "" ? this.id : this.key,
      data: this,
    });
  }

  /**
   * Removes the menu from the global storage object.
   *
   * @protected
   */
  _unstore() {
    if (
      !isValidInstance(
        StorageManager,
        { storage: window.AccessibleMenu },
        { shouldThrow: false }
      ).status
    ) {
      return;
    }

    window.AccessibleMenu.clear({
      key: this.id !== "" ? this.id : this.key,
    });
  }

  /**
   * Sets the transition durations of the menu as a CSS custom properties.
   *
   * The custom properties are:
   *   - `--am-transition-duration`,
   *   - `--am-open-transition-duration`, and
   *   - `--am-close-transition-duration`.
   *
   * The prefix of `am-` can be changed by setting the menu's prefix value.
   *
   * @protected
   */
  _setTransitionDurations() {
    this.dom.menu.style.setProperty(
      `--${this.prefix}transition-duration`,
      `${this.transitionDuration}ms`
    );

    this.dom.menu.style.setProperty(
      `--${this.prefix}open-transition-duration`,
      `${this.openDuration}ms`
    );

    this.dom.menu.style.setProperty(
      `--${this.prefix}close-transition-duration`,
      `${this.closeDuration}ms`
    );
  }

  /**
   * Sets a timeout within the menu.
   *
   * @protected
   *
   * @param {Function} [callback]         - The callback function.
   * @param {number}   [delay]            - The time (in milliseconds) of the delay.
   * @param {string}   [scope = _default] - The scope of the timeout (used to store the timeout in _timeouts).
   */
  _setTimeout(callback, delay, scope = "_default") {
    this._clearTimeout(scope);

    this._timeouts[scope] = setTimeout(callback, delay);
  }

  /**
   * Clears a timeout within the menu.
   *
   * @protected
   *
   * @param {string} [scope = _default] - The scope of the timeout (used to get the timeout from _timeouts).
   */
  _clearTimeout(scope = "_default") {
    clearTimeout(this._timeouts[scope]);
  }

  /**
   * Clears all timeouts within the menu.
   *
   * @protected
   */
  _clearTimeouts() {
    for (const scope of Object.keys(this._timeouts)) {
      this._clearTimeout(scope);
    }
  }

  /**
   * Add an event listener to an element and register it within the menu.
   *
   * @param {string}         type           - The type of event to listen for.
   * @param {HTMLElement}    element        - The element to add the listener to.
   * @param {Function}       listener       - The listener callback.
   * @param {object|boolean} [options = {}] - Options to pass to the listener.
   */
  _addEventListener(type, element, listener, options = {}) {
    // Add the listener.
    element.addEventListener(type, listener, options);

    // Store it in the menu.
    this._listeners.push({
      type,
      element,
      listener,
      options,
    });
  }

  /**
   * Remove an event listener from an element and unregister it within the menu.
   *
   * @param {string}         type           - The type of event to remove.
   * @param {HTMLElement}    element        - The element to remove the listener from.
   * @param {Function}       listener       - The listener callback.
   * @param {object|boolean} [options = {}] - Options to pass to the listener.
   */
  _removeEventListener(type, element, listener, options = {}) {
    // Remove the listener.
    element.removeEventListener(type, listener, options);

    // Find the listener in the menu's listener storage.
    let index = -1;

    this._listeners.forEach((registeredListener, i) => {
      if (
        registeredListener.type === type &&
        registeredListener.element === element &&
        registeredListener.listener === listener &&
        JSON.stringify(registeredListener.options) === JSON.stringify(options)
      ) {
        index = i;
      }
    });

    // Remove it from the menu's listener storage.
    if (index !== -1) {
      this._listeners.splice(index, 1);
    }
  }

  /**
   * Removes all event listeners registered in the menu.
   *
   * This can be filtered by type and/or element.
   *
   * @protected
   *
   * @param {object}       [options = {}]           - Options for removing listeners.
   * @param {?string}      [options.type = null]    - The type of event to remove. If null, all types are removed.
   * @param {?HTMLElement} [options.element = null] - The element to remove listeners from. If null, all elements are removed.
   */
  _removeEventListeners({ type = null, element = null } = {}) {
    const listeners = [...this._listeners];

    listeners.forEach((listener) => {
      if (type !== null && listener.type !== type) return;
      if (element !== null && listener.element !== element) return;

      this._removeEventListener(
        listener.type,
        listener.element,
        listener.listener,
        listener.options
      );
    });
  }

  /**
   * Focus the menu.
   *
   * Sets the menu's focus state to "self" and
   * focusses the menu if the menu's shouldFocus
   * value is `true`.
   *
   * @public
   */
  focus() {
    this.focusState = "self";

    if (this.shouldFocus) {
      this.dom.menu.focus();
    }
  }

  /**
   * Unfocus the menu.
   *
   * Sets the menu's focus state to "none"
   * and blurs the menu if the menu's shouldFocus
   * value is `true`.
   *
   * @public
   */
  blur() {
    this.focusState = "none";

    if (this.shouldFocus) {
      this.dom.menu.blur();
    }
  }

  /**
   * Focus the menu's current child.
   *
   * @public
   */
  focusCurrentChild() {
    this.focusState = "self";

    if (this.currentChild !== -1) {
      this.currentMenuItem.focus();
    }
  }

  /**
   * Focuses the menu's child at a given index.
   *
   * @public
   *
   * @param {number} index - The index of the child to focus.
   */
  focusChild(index) {
    this.blurCurrentChild();
    this.currentChild = index;
    this.focusCurrentChild();
  }

  /**
   * Focuses the menu's first child.
   *
   * @public
   */
  focusFirstChild() {
    this.focusChild(0);
  }

  /**
   * Focus the menu's last child.
   *
   * @public
   */
  focusLastChild() {
    this.focusChild(this.elements.menuItems.length - 1);
  }

  /**
   * Focus the menu's next child.
   *
   * @public
   */
  focusNextChild() {
    if (this.currentChild < this.elements.menuItems.length - 1) {
      this.focusChild(this.currentChild + 1);
    } else {
      this.focusCurrentChild();
    }
  }

  /**
   * Focus the menu's previous child.
   *
   * @public
   */
  focusPreviousChild() {
    if (this.currentChild > 0) {
      this.focusChild(this.currentChild - 1);
    } else {
      this.focusCurrentChild();
    }
  }

  /**
   * Blurs the menu's current child.
   *
   * @public
   */
  blurCurrentChild() {
    this.focusState = "none";

    if (this.currentChild !== -1) {
      this.currentMenuItem.blur();
    }
  }

  /**
   * Focus the menu's controller.
   *
   * @public
   */
  focusController() {
    if (this.dom.controller) {
      if (this.shouldFocus) {
        this.dom.controller.focus();
      }

      this.focusState = "none";
    }
  }

  /**
   * Focus the menu's container.
   *
   * @public
   */
  focusContainer() {
    if (this.dom.container) {
      if (this.shouldFocus) {
        this.dom.container.focus();
      }

      this.focusState = "none";
    }
  }

  /**
   * Close all submenu children.
   *
   * @public
   */
  closeChildren() {
    this.elements.submenuToggles.forEach((toggle) => toggle.close());
  }

  /**
   * Blurs all children and submenu's children.
   *
   * @public
   */
  blurChildren() {
    this.elements.menuItems.forEach((menuItem) => {
      menuItem.blur();

      if (menuItem.isSubmenuItem) {
        menuItem.elements.childMenu.blurChildren();
      }
    });
  }

  /**
   * Disposes of the menu.
   *
   * Removes all event listeners, clears all timeouts, removes the menu from storage, and deletes the menu instance.
   */
  dispose() {
    this._removeEventListeners();
    this._clearTimeouts();
    this._unstore();

    delete this;
  }
}

export default BaseMenu;
